### ISSUE TITLE
🐛 OAuth 리다이렉트 uri 오류

### ISSUE THREAD

**Issue by Seotephen** [bitbit-Merry-go-round/Transcendence-FE#88]
## 🔎 어떤 버그인가요?
- OAuth 리다이렉트 uri 오류
- uri가 127.0.0.1로 되어있어서 서버를 통해 로그인을 할 수 없습니다.
- 서버로 사용할 컴퓨터를 고정해놓고 redirect uri를 재등록 해야할 것 같아요.

## 📝 어떤 상황에서 발생한 버그인가요?
- 원격으로 서비스 접근 시 로그인 불가

## 🧪 예상 결과
> 로그인 가능 및 서비스 이용 가능

## ✅ To-do
- [ ] login 뷰에서 redirect uri 변경
- [ ] CORS_ALLOWED_ORIGINS에 해당 uri 추가 (BE)
- [ ] ALLOWED_HOSTS에 해당 uri 추가 (BE)

## 📚 참고할만한 자료
<img width="1203" alt="image" src="https://github.com/bitbit-Merry-go-round/Transcendence-FE/assets/99523863/0c921c7c-9043-4b43-8c16-f8cbf1d00e07">
